services:
  db:
    image: pgvector/pgvector:pg15
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_graphrag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: